### ISSUE TITLE
'estimatefee' and 'estimatesmartfee' in chips-cli fail

### ISSUE THREAD

**Issue by who-biz** [chips-blockchain/lightning#11]
### Issue and Steps to Reproduce

With a running `chipsd`, the following responses are given when `chips-cli` is sent `estimatefee` and `estimatesmartfee` commands respectively:

**estimatefee:**
```shell
$ chips-cli estimatefee

error code: -32
error message:
estimatefee was removed in v0.17.
Clients should use estimatesmartfee.
```

**estimatesmartfee:**

```
$ chips-cli estimatesmartfee 5

{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 5
}
```
---

### Related `lightningd` Errors

Following `UNUSUAL` logging on init, and periodically while running `lightningd`:

```
 UNUSUAL lightningd: Unable to estimate opening fees
 UNUSUAL lightningd: Unable to estimate mutual_close fees
 UNUSUAL lightningd: Unable to estimate unilateral_close fees
 UNUSUAL lightningd: Unable to estimate delayed_to_us fees
 UNUSUAL lightningd: Unable to estimate htlc_resolution fees
 UNUSUAL lightningd: Unable to estimate penalty fees
 UNUSUAL lightningd: Unable to estimate min_acceptable fees
 UNUSUAL lightningd: Unable to estimate max_acceptable fees
```

**Comment by sg777** [comment]
This is not a fix, if this is blocking, you can hard set the tx fee to `0.0005` to test other ln functionalities.

**Comment by satindergrewal** [comment]
I applied static fee conditionally in `c-lightning` only for CHIPS network in this git commit, and few prior to that: https://github.com/chips-blockchain/lightning/commit/086652ce6c3230e291dd2c90fcb7b0c5740f9397

It is all set in satshi value of 50,000 satoshies.

And after this change I'm able to connect the peer between new and old `c-lightning` forks we are using in CHIPS development, and able to get answer in `listpeers` command as expected. `fundchannel` also worked perfectly fine after this issue resolved by statically setting the fees.

I think you can check, test and may be close this issue if it resolves the issue for you.
Or in case any testing shows the static value setting isn't resolving the issue, please report back here so we can collectively give it another try to fix it.

Thanks for your help @who-biz. It's been really helpful even with the hits and tries you did to resolve the other 2 issues.

**Comment by who-biz** [comment]
Will check this now, and close once confirmed... Re-syncing to chain tip currently.

And no problem! Happy to help.

**Comment by who-biz** [comment]
confirmed resolved on `lightning` side: 

```
~$ lightning-cli estimatefees
{
   "opening": 5000,
   "mutual_close": 5000,
   "unilateral_close": 5000,
   "delayed_to_us": 5000,
   "htlc_resolution": 5000,
   "penalty": 5000,
   "min_acceptable": 2500,
   "max_acceptable": 50000
}
```
