### ISSUE TITLE
"listpeers" does not show any peer connected after "connect" peer command

### ISSUE THREAD

**Issue by satindergrewal** [chips-blockchain/lightning#9]
### Issue and Steps to Reproduce
On latest fork of `c-lightning` from `tor` branch of this repository, following commands fail to show peer after multiple tries of connecting to local peer with it's public IP, local IP, or global range IP (0.0.0.0).

### Commands output

```bash
# Checking available funds in this lightning node
satinder@player1:~/grewal/lightning$ cli/lightning-cli listfunds
{
   "outputs": [
      {
         "txid": "749f542a0ab90780fad9e1f52262fcae46d681a5536ad8cce1dd6e04c961832e",
         "output": 0,
         "value": 25050000,
         "amount_msat": "25050000000msat",
         "redeemscript": "001411deffab7a66aa22c6dcb13352d81de3e2ec2a42",
         "scriptpubkey": "a914a1d78c8a8e74d00cbd886fefe3c0471c76332ce387",
         "address": "bTV1hipJDko3tP2CXXNhZCR68hbe6ZuoZj",
         "status": "confirmed",
         "blockheight": 7723534,
         "reserved": false
      },
      {
         "txid": "bf65387f917ae5eac65e2ed7a6c5a262ca2c507c8d06abfd640102dc6d8168a9",
         "output": 0,
         "value": 100000000,
         "amount_msat": "100000000000msat",
         "redeemscript": "0014f20910078efcebed35af04f551ecbeccc4a96174",
         "scriptpubkey": "a9144f5ae88e9dde87f6305d614e357789f1bd67783b87",
         "address": "bKxryp8z6JXEn9RXrhMD5Tsh2Gnq39GxbT",
         "status": "confirmed",
         "blockheight": 7740735,
         "reserved": false
      }
   ],
   "channels": []
}

# Identifying this node's ID and other info like IPv4 etc.
satinder@player1:~/grewal/lightning$ cli/lightning-cli getinfo
{
   "id": "02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2",
   "alias": "SLIMYTRINITY",
   "color": "02ee01",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "51.222.150.52",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "chipsln.0.0.0",
   "blockheight": 7741618,
   "network": "chips",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/satinder/.chipsln/chips"
}

# Funding a channel on this node
satinder@player1:~/grewal/lightning$ cli/lightning-cli fundchannel 02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2 1000
{
   "code": -32602,
   "message": "destinations: output would be dust: invalid token '{\"id\":\"02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2\",\"amount\":1000}'"
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli fundchannel 02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2 100000
{
   "code": 400,
   "message": "'connect' failed",
   "data": {
      "id": "02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2",
      "method": "connect",
      "error": {
         "code": 400,
         "message": "Unable to connect, no address known for peer"
      }
   }
}

# Trying to connect to this node's own IP and still failing to get any peer in list
satinder@player1:~/grewal/lightning$ cli/lightning-cli listpeers
{
   "peers": []
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli connect 02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2@51.222.150.52:9735
{
   "id": "02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2",
   "features": "02aaa2"
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli listpeers
{
   "peers": []
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli connect 02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2@127.0.0.1
{
   "id": "02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2",
   "features": "02aaa2"
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli listpeers
{
   "peers": []
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli connect 02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2@0.0.0.0
{
   "id": "02ee01b7e8597ad1dea110a89791f529a563e55031660c1fba2a08ff4d6395c6a2",
   "features": "02aaa2"
}
satinder@player1:~/grewal/lightning$ cli/lightning-cli listpeers
{
   "peers": []
}
```

#### Results from old fork of `c-lightning`
The same set of commands shows the peer fine in old fork of `c-lightning`, which is in `master` branch of this repository:

#### Old fork's commands outputs

```bash
# Getting this node's ID and IP info
satinder@dealer1:~$ lightning-cli getinfo | jq .
{
  "id": "03ec60cdd935305bbd277839df1125308d8e69a5c76272fefeedf5815b5eb097ae",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "51.222.150.55",
      "port": 9735
    }
  ],
  "version": "chipsln.0.0.0",
  "blockheight": 7741638,
  "network": "chips"
}

# Checking this node's funds
satinder@dealer1:~$ lightning-cli listfunds | jq .
{
  "outputs": [],
  "channels": []
}

# Geenrate a new address to send funds to from CHIPS blockchain, which is Bitcoin-Core fork
satinder@dealer1:~$ lightning-cli newaddr | jq .
{
  "address": "bYtsvUJEsJeFfxn2gG2RH5P42sxytiwLm7"
}

# Checking available funds after sending CHIPS coins to the newly generated lightning address
satinder@dealer1:~$ lightning-cli listfunds | jq .
{
  "outputs": [
    {
      "txid": "8c1eef5c6c7adb5c0fddddbe28fdf02d6381c4491f87b951d5ae16b1a61de467",
      "output": 0,
      "value": 10000000,
      "status": "confirmed"
    }
  ],
  "channels": []
}

# Try to connect to this node's own IP and lightning node ID as a peer
satinder@dealer1:~$ lightning-cli connect 03ec60cdd935305bbd277839df1125308d8e69a5c76272fefeedf5815b5eb097ae@51.222.150.55
{ "id" : "03ec60cdd935305bbd277839df1125308d8e69a5c76272fefeedf5815b5eb097ae" }

# Checking if the listpeers command outputs any connected peers. And in this old fork of `c-lightning` code, it works as expected.
satinder@dealer1:~$ lightning-cli listpeers | jq .
{
  "peers": [
    {
      "state": "GOSSIPING",
      "id": "034560c6506fb70ca666708f7c9b716b794e3449466d4450171670e1c18e4e6cb8",
      "netaddr": [
        "[::ffff:51.222.150.54]:58140"
      ],
      "connected": true,
      "owner": "lightning_gossipd"
    }
  ]
}
```

**Comment by who-biz** [comment]
Posting my progress from testing last week here:

I was able to reproduce this behavior, as well as that mentioned in #8, despite not seeing the `peer-channel-state` issue until today.  As a means to check what workarounds may be possible, and to find primary location of error, I think the following procedure may be helpful.  However, it did not solve anything in my tests conducted before the weekend.

When running `lightningd`, I wanted to figure out which subdaemon is actually the culprit in this failure.  I compiled the most recent version of https://github.com/ElementsProject/lightning, and am going to specify subdaemons using the following:

```
--subdaemon <arg>                           Arg specified as SUBDAEMON:PATH. Specifies an alternate subdaemon binary.
```

Which needs launched in conjunction with: 

```
--dev-no-version-checks                     Skip calling subdaemons with --version on startup
```

Otherwise, the `lightningd` will fail to launch due to incompat subd version.

 I did this using ElementProject's `openingd` on Friday, which did produced the same behavior we're seeing above (read: fixed nohing).  So, either the problem is not fixed upstream, or `openingd` is not the source of the issue.

---

Aside from just procedural tests, I did some digging into code to figure out where things are going awry.  I was able to connect to remote node addresses from LN explorer, which then return proper results for `listpeers`, once connected.

This tells me problem is likely coming from handling of our own node's peer ID, or something with initializattion of file descriptors (`fd`), when we're figuring these out with our local node.

 These `fd` entries are used to discern a few things about our connections, and are populated in our `peer_peer_state` struct (see below), as well as a few others which store information for various subdaemons.
 
https://github.com/chips-blockchain/lightning/blob/9cbd150263c65fd03ca2a2d03ea6eddf7f183696/common/per_peer_state.h#L17-L27
 
 The failure I'm seeing is occurring with logging that reads: `Failed to read header: Success` from here:
 
 https://github.com/chips-blockchain/lightning/blob/9cbd150263c65fd03ca2a2d03ea6eddf7f183696/common/crypto_sync.c#L105-L108
 
 This same behavior can be seen in this issue: https://github.com/ElementsProject/lightning/issues/4318 upstream.  I'm not yet sure if our issue is stemming from the same problem.

**Comment by who-biz** [comment]
@satindergrewal Out of curiosity, have you configured `tor` on the node in question?  I have not done so, and am wondering if the problem may be in localhost proxy routing that `lightningd` is expecting of `tor` through `127.0.0.1:9050`.

**Comment by sg777** [comment]
@who-biz in the existing(old fork) ln repo, we haven't done any configuration for tor. Is it mandate to setup tor to use the latest ln repo?

**Comment by satindergrewal** [comment]
> @satindergrewal Out of curiosity, have you configured `tor` on the node in question? I have not done so, and am wondering if the problem may be in localhost proxy routing that `lightningd` is expecting of `tor` through `127.0.0.1:9050`.

Nope, I haven’t tested with Tor setup at all. And for this testing no need to test the setup with tor settings until everything works like usual in plain internet itself.

Once things are working as expected over internet, then we will need to test tor. Not until then.

**Comment by satindergrewal** [comment]
> @who-biz in the existing(old fork) ln repo, we haven't done any configuration for tor. Is it mandate to setup tor to use the latest ln repo?

No, it is not mandatory to use tor in new update. New or latest updates include support of tor connection and onion routing support to c-lightning. It is optional to configure tor for a node.

**Comment by satindergrewal** [comment]
After this git commit https://github.com/chips-blockchain/lightning/commit/086652ce6c3230e291dd2c90fcb7b0c5740f9397 the issue seems to be resolved. Bit more details added here: https://github.com/chips-blockchain/lightning/issues/11#issuecomment-830651397

The issue seemed to be related to `estimatefees` API not giving expected satoshi fees value, and instead of giving `NULL` output. By setting static fees value in `c-lightning` conditionally for CHIPS things seems to be working as expected.

 It is reflecting expected output for `listpeers` command after connecting remote peers.

So, I'm closing this issue for now, and if the issue still persists or shows up again, we can open this issue again, or make a new one.
